import { ch, inp, fix, ord, group, p, html, extend } from "./_helpers.mjs";

const intro = (lesson, topics) => html(
  p(`Проверка по уроку <b>${lesson}</b>. Новые задания, которых не было в уроке.`),
  p(`<b>Что проверяем:</b> ${topics}`),
  p("Решайте без подсказок и не открывайте объяснения. Итог внизу страницы покажет, сколько решено с первой попытки. Ошибки попадут в «Мои ошибки», их можно перерешать.")
);

const lesson = {
  slug: "tests",
  title: "Контрольные работы",
  subtitle: "по контрольной на каждый урок и большая итоговая по всему курсу",
  position: 7,
  steps: false,
  sections: [
    {
      id: "t1", nav: "К1 · to be", eyebrow: "Контрольная 1 · урок 1", title: "Глагол to be",
      theory: intro("1 «Глагол to be»", "am / is / are · отрицания · вопросы и короткие ответы · where / what / how · порядок слов · страны · its / it's · -ing / -ed · перевод · was / were"),
      groups: [
        group("Часть A · выберите", [
          ch("My cousins ___ from Brazil.", ["am", "is", "are"], "are", "cousins = they → are."),
          ch("The weather ___ terrible today.", ["am", "is", "are"], "is", "weather = it → is."),
          ch("I ___ not ready yet.", ["am", "is", "are"], "am", "I → am."),
          ch("___ your office far from here?", ["Am", "Is", "Are"], "Is", "office = it → Is."),
          ch("Are you and Kate sisters? — Yes, ___.", ["we are", "we're", "they are"], "we are", "you and Kate → we. Короткое «да» без сокращения."),
          ch("Is the museum open on Mondays? — No, ___.", ["it isn't", "it not", "isn't"], "it isn't", "No, it isn't."),
          ch("___ is your birthday? — In May.", ["Where", "When", "Who"], "When", "In May — когда → When."),
          ch("___ are you from? — I'm from Kazan.", ["What", "Where", "How"], "Where", "Откуда → Where … from."),
          ch("He's from Sweden. He's ___.", ["Swedish", "Swedian", "Swede's"], "Swedish", "Sweden → Swedish."),
          ch("The hotel is famous for ___ view.", ["it's", "its"], "its", "Чей вид? Отеля → its."),
          ch("I'm ___ in art.", ["interesting", "interested"], "interested", "Мне интересно → I'm interested."),
          ch("«Мне скучно.»", ["I'm bored.", "I'm boring.", "Me is boring."], "I'm bored.", "Состояние человека → bored."),
          ch("I ___ at home yesterday.", ["am", "was", "were"], "was", "yesterday → прошлое, I → was."),
          ch("Look! The children ___ playing in the snow.", ["is", "are", "—"], "are", "Прямо сейчас: are + playing."),
        ]),
        group("Часть B · напишите", [
          inp("They are at the office.", ["They aren't at the office.", "They are not at the office.", "They're not at the office."], "are → aren't.", "Сделайте отрицание"),
          inp("Your brother is married.", ["Is your brother married?"], "Is + your brother + married?", "Превратите в вопрос"),
          inp("«Мне 30 лет.»", ["I'm 30.", "I am 30.", "I'm 30 years old.", "I am 30 years old.", "I'm thirty.", "I am thirty."], "Возраст — через to be.", "Переведите на английский"),
          inp("«Где твои ключи?»", ["Where are your keys?"], "keys → are.", "Переведите на английский"),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          fix("My parents is on holiday.", "is", "are", "parents = they → are."),
          fix("I amn't hungry.", "amn't", "am not", "Формы amn't нет: I'm not / I am not."),
          ord("What is your favourite film?", "What + is + your favourite film?"),
          ord("It is very cold today.", "It + is + very cold + today."),
        ]),
      ],
    },
    {
      id: "t2", nav: "К2 · whose", eyebrow: "Контрольная 2 · урок 2", title: "Чьё это? Вещи и принадлежность",
      theory: intro("2 «Чьё это?»", "вещи · this / these / that / those · my / your… · mine / yours… · whose · 's · inside / outside, pleasant"),
      groups: [
        group("Часть A · выберите", [
          ch("«солнцезащитные очки» — ___", ["sunglasses", "sunglass", "sun glass"], "sunglasses", "Всегда во множественном: sunglasses."),
          ch("«кошелёк для денег» — ___", ["wallet", "charger", "scarf"], "wallet", "wallet — кошелёк."),
          ch("My earrings ___ in the bathroom.", ["is", "are"], "are", "earrings — несколько → are."),
          ch("___ are my new shoes. Do you like them? (они у вас на ногах)", ["This", "These", "Those"], "These", "Близко и несколько → These."),
          ch("Who is ___ woman over there?", ["this", "that", "those"], "that", "Далеко, одна → that."),
          ch("Ben can't find ___ phone.", ["his", "her", "him"], "his", "Ben → his."),
          ch("The cat is eating. ___ food is in the kitchen.", ["It's", "Its", "Her"], "Its", "Кошка → its."),
          ch("That laptop isn't ___. It's my brother's.", ["my", "mine", "me"], "mine", "Без предмета → mine."),
          ch("Is this scarf ___, Anna?", ["your", "yours", "you"], "yours", "Без предмета → yours."),
          ch("___ car is this? — It's Mike's.", ["Who", "Who's", "Whose"], "Whose", "Чья? → Whose."),
          ch("This is my ___ room. (у меня две сестры, комната общая)", ["sister's", "sisters'", "sisters's"], "sisters'", "Две сёстры: sisters + ' → sisters'."),
          ch("It's raining. Let's stay ___.", ["outside", "inside"], "inside", "Дождь → останемся внутри."),
          ch("These gloves aren't ours. They're ___. (Tom and Lisa)", ["their", "theirs", "them"], "theirs", "they → theirs."),
        ]),
        group("Часть B · напишите", [
          inp("This is Kate's notebook. → This notebook is ___.", ["hers"], "Kate → she → hers.", "Впишите одно слово", "she → h…"),
          inp("That is my key.", ["Those are my keys."], "that → those, is → are, key → keys.", "Напишите про несколько предметов"),
          inp("(these / sunglasses)", ["Whose sunglasses are these?", "Whose are these sunglasses?"], "Whose + sunglasses + are + these?", "Спросите: «Чьи это очки?»"),
          inp("Are these your gloves?", ["Are these yours?", "Are they yours?"], "your gloves → yours.", "Замените с помощью mine, yours, hers…"),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          fix("Who's bag is this?", "Who's", "Whose", "Чья? → Whose."),
          fix("This are my keys.", "This", "These", "keys — несколько → These are."),
          fix("Is this pen your?", "your", "yours", "Без предмета → yours."),
          ord("Whose wallet is on the table?", "Whose wallet + is + on the table?"),
          ord("That is my father's car.", "my father's + car.", [], []),
        ]),
      ],
    },
    {
      id: "t3", nav: "К3 · have got", eyebrow: "Контрольная 3 · урок 3", title: "have got — у меня есть",
      theory: intro("3 «have got»", "have got / has got · haven't got · Have you got…? и короткие ответы · have и do you have · 's = is или has · прилагательные · everything / everybody"),
      groups: [
        group("Часть A · выберите", [
          ch("My grandparents ___ a small house in the country.", ["have got", "has got"], "have got", "grandparents = they → have got."),
          ch("Anna ___ long dark hair.", ["have got", "has got"], "has got", "Anna = she → has got."),
          ch("He's got two cars. — 's = ___", ["is", "has"], "has", "'s + got → has."),
          ch("He's very tall. — 's = ___", ["is", "has"], "is", "got нет → is."),
          ch("We ___ any bread. Can you buy some?", ["haven't got", "hasn't got"], "haven't got", "we → haven't got."),
          ch("___ your brother got a girlfriend?", ["Have", "Has", "Does"], "Has", "brother = he → Has."),
          ch("Have you got a pet? — No, I ___.", ["haven't", "haven't got", "don't"], "haven't", "Без got: No, I haven't."),
          ch("Do you have a bike? — Yes, I ___.", ["have", "do", "have got"], "do", "Вопрос с Do → Yes, I do."),
          ch("She doesn't ___ a job.", ["has", "have", "has got"], "have", "После doesn't — have."),
          ch("My old laptop is very ___. I can't carry it every day.", ["light", "heavy", "soft"], "heavy", "Трудно носить → тяжёлый: heavy."),
          ch("This sofa is really ___. I love sitting on it.", ["broken", "comfortable", "square"], "comfortable", "Приятно сидеть → comfortable."),
          ch("Everybody ___ tired after the trip.", ["is", "are"], "is", "После everybody — is."),
          ch("«У меня нет вопросов.» — I haven't got ___ questions.", ["some", "any", "a"], "any", "Отрицание + мн. число → any."),
        ]),
        group("Часть B · напишите", [
          inp("He has got a car.", ["He hasn't got a car.", "He has not got a car."], "has got → hasn't got.", "Сделайте отрицание"),
          inp("you / a brother?", ["Have you got a brother?"], "Have + you + got + a brother?", "Составьте вопрос с have got"),
          inp("Has she got a dog?", ["Does she have a dog?"], "Has she got → Does she have.", "Перепишите с do / does"),
          inp("heavy →", ["light"], "heavy ↔ light.", "Напишите противоположное прилагательное", "Начинается на l."),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          fix("My sister have got a new job.", "have", "has", "sister = she → has got."),
          fix("Do you have got a pen?", "Do", "Have", "С got: Have you got a pen?"),
          fix("I've got two news phones.", "news", "new", "Прилагательное без -s."),
          ord("How many cousins have you got?", "How many cousins + have + you + got?"),
          ord("We haven't got any time now.", "We + haven't got + any time + now."),
        ]),
      ],
    },
    {
      id: "t4", nav: "К4 · I / you / we", eyebrow: "Контрольная 4 · урок 4", title: "Present Simple: I, you, we, they",
      theory: intro("4 «Present Simple: I, you, we, they»", "утверждение · don't · Do…? и короткие ответы · свободное время · like + -ing · always … never · at / on / in · once a week · дни и месяцы"),
      groups: [
        group("Часть A · выберите", [
          ch("I ___ in a bank.", ["work", "am work", "working"], "work", "Одно сказуемое — work."),
          ch("We ___ very happy here.", ["are", "—"], "are", "happy — не действие → are."),
          ch("They ___ meat.", ["don't eat", "not eat", "aren't eat"], "don't eat", "Отрицание: don't + eat."),
          ch("___ you speak French?", ["Are", "Do", "Have"], "Do", "speak — действие → Do."),
          ch("Do your friends live near you? — No, they ___.", ["don't", "aren't", "not"], "don't", "No, they don't."),
          ch("I often ___ for a walk after dinner.", ["go", "do", "make"], "go", "go for a walk."),
          ch("We ___ friends every Friday.", ["meet", "meet with", "go"], "meet", "meet friends."),
          ch("I love ___ in the sea.", ["swim", "swimming", "swims"], "swimming", "love + V-ing."),
          ch("(sometimes)", ["We sometimes eat out.", "We eat sometimes out.", "We eat out sometimes not."], "We sometimes eat out.", "Перед глаголом."),
          ch("(never)", ["I never watch horror films.", "I don't never watch horror films.", "I watch never horror films."], "I never watch horror films.", "never без don't."),
          ch("(always)", ["You're always late!", "You always are late!", "Always you're late!"], "You're always late!", "После are."),
          ch("My English lessons are ___ Tuesdays.", ["at", "on", "in"], "on", "Дни недели → on."),
          ch("We go skiing ___ winter.", ["at", "on", "in"], "in", "Время года → in."),
          ch("The film starts ___ 8.30.", ["at", "on", "in"], "at", "Точное время → at."),
          ch("«Я хожу в бассейн два раза в неделю.»", ["I go to the pool twice a week.", "I go to the pool two times in week.", "I twice go to the pool a week."], "I go to the pool twice a week.", "twice a week — в конце."),
        ]),
        group("Часть B · напишите", [
          inp("We watch TV in the evening.", ["We don't watch TV in the evening.", "We do not watch TV in the evening."], "watch → don't watch.", "Сделайте отрицание"),
          inp("You like jazz.", ["Do you like jazz?"], "Do + you + like jazz?", "Превратите в вопрос"),
          inp("четверг →", ["Thursday"], "Thursday — с большой буквы.", "Напишите день недели", "Thu…"),
          inp("декабрь →", ["December"], "December — с большой буквы.", "Напишите месяц", "Dec…"),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          ch("«Я живу в Казани.»", ["I live in Kazan.", "I am live in Kazan.", "I living in Kazan."], "I live in Kazan.", "live — действие, am не нужен."),
          fix("We don't got a garden.", "got", "have", "После don't — have."),
          ord("I usually go to bed at eleven.", "I + usually + go to bed + at eleven."),
          ord("They play tennis twice a week.", "They + play tennis + twice a week."),
          ord("We don't often go to the cinema.", "We + don't + often + go to the cinema."),
        ]),
      ],
    },
    {
      id: "t5", nav: "К5 · he / she / it", eyebrow: "Контрольная 5 · урок 5", title: "Present Simple: he, she, it",
      theory: intro("5 «Present Simple: he, she, it»", "окончание -s / -es / -ies · doesn't · Does…? и короткие ответы · распорядок дня · профессии · числа"),
      groups: [
        group("Часть A · выберите", [
          ch("My mum ___ in a school.", ["work", "works", "working"], "works", "mum = she → works."),
          ch("Tom ___ his teeth after breakfast.", ["brush", "brushs", "brushes"], "brushes", "sh → es."),
          ch("She ___ German at university.", ["studys", "studies", "study"], "studies", "согласная + y → ies."),
          ch("He ___ football every Sunday.", ["plaies", "plays", "play"], "plays", "гласная + y → s."),
          ch("My brother ___ a motorbike.", ["has", "have", "haves"], "has", "have → has."),
          ch("Liam ___ breakfast.", ["don't have", "doesn't have", "doesn't has"], "doesn't have", "doesn't + have."),
          ch("___ your dad cook?", ["Do", "Does", "Is"], "Does", "dad = he → Does."),
          ch("Does Maria speak English? — Yes, she ___.", ["does", "speaks", "do"], "does", "Yes, she does."),
          ch("Does the shop open on Sundays? — No, it ___.", ["doesn't", "don't", "isn't"], "doesn't", "No, it doesn't."),
          ch("She ___ dressed very quickly.", ["gets", "does", "makes"], "gets", "get dressed."),
          ch("I ___ home at about 7 p.m.", ["get", "get to", "go to"], "get", "get home — без to."),
          ch("He works in a hospital. He isn't a doctor. He's a ___.", ["nurse", "farmer", "driver"], "nurse", "В больнице, не врач → nurse."),
          ch("«Он журналист.»", ["He's a journalist.", "He's journalist.", "He journalist."], "He's a journalist.", "a перед профессией."),
          ch("14 — ___", ["forty", "fourteen", "fourty"], "fourteen", "14 = fourteen."),
        ]),
        group("Часть B · напишите", [
          inp("fix →", ["fixes"], "x → es.", "Напишите глагол для he / she / it", "Кончается на x."),
          inp("worry →", ["worries"], "согласная + y → ies.", "Напишите глагол для he / she / it", "y меняется."),
          inp("She drives to work.", ["She doesn't drive to work.", "She does not drive to work."], "drives → doesn't drive.", "Сделайте отрицание"),
          inp("He finishes work at five.", ["Does he finish work at five?"], "Does + he + finish…?", "Превратите в вопрос"),
          inp("your sister / what / do?", ["What does your sister do?"], "What + does + your sister + do?", "Составьте вопрос о профессии"),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          fix("She don't like coffee.", "don't", "doesn't", "she → doesn't."),
          fix("Does he works on Saturdays?", "works", "work", "После Does — work."),
          fix("My dad watchs the news every evening.", "watchs", "watches", "ch → es."),
          ord("He gets up at six every day.", "He + gets up + at six + every day."),
          ord("Where does your brother work?", "Where + does + your brother + work?"),
        ]),
      ],
    },
    {
      id: "t6", nav: "К6 · вопросы", eyebrow: "Контрольная 6 · урок 6", title: "Вопросы: do, does и to be",
      theory: intro("6 «Вопросы: do, does и to be»", "Do / Does…? и ever · Where / What time / How often…? · предлог в конце вопроса · to be или do · play / listen to / watch / go to · much / many"),
      groups: [
        group("Часть A · выберите", [
          ch("___ you ever go to concerts?", ["Do", "Are", "Does"], "Do", "go — действие, you → Do."),
          ch("How often ___ she go swimming?", ["do", "does", "is"], "does", "she → does."),
          ch("What time ___ the train leave?", ["do", "does", "is"], "does", "train = it → does."),
          ch("Where ___ your parents from?", ["do", "are", "does"], "are", "from — откуда → to be: are."),
          ch("Where ___ your parents live?", ["do", "are", "does"], "do", "live — действие → do."),
          ch("___ he a good cook?", ["Is", "Does"], "Is", "a good cook — кто → Is."),
          ch("___ he cook well?", ["Is", "Does"], "Does", "cook — действие → Does."),
          ch("___ you hungry?", ["Are", "Do"], "Are", "hungry — какой → Are."),
          ch("«Кто твой любимый певец?»", ["Who is your favourite singer?", "What is your favourite singer?", "Who does your favourite singer?"], "Who is your favourite singer?", "О человеке — Who is."),
          ch("«О чём эта книга?»", ["What is this book about?", "About what this book is?", "What does this book about?"], "What is this book about?", "Предлог about — в конце."),
          ch("I ___ to podcasts in the car.", ["listen", "listen to", "watch"], "listen to", "listen to."),
          ch("Do you ___ the guitar?", ["play", "go", "listen to"], "play", "play the guitar."),
          ch("How ___ money have you got?", ["much", "many"], "much", "money нельзя посчитать → much."),
          ch("How ___ languages do you speak?", ["much", "many"], "many", "languages → many."),
        ]),
        group("Часть B · задайте вопрос", [
          inp("I live in Samara.", ["Where do you live?"], "Where + do + you + live?", "Спросите: «Где ты живёшь?»"),
          inp("She starts work at nine.", ["What time does she start work?", "When does she start work?"], "What time + does + she + start work?", "Спросите: «Во сколько она начинает работу?»"),
          inp("They go to the gym three times a week.", ["How often do they go to the gym?"], "How often + do + they + go…?", "Спросите: «Как часто они ходят в спортзал?»"),
          inp("This jacket costs £80.", ["How much does this jacket cost?", "How much is this jacket?", "How much does it cost?", "How much is it?"], "How much + does + it + cost?", "Спросите: «Сколько стоит эта куртка?»"),
          inp("He is 35.", ["How old is he?"], "Возраст → How old is he?", "Спросите: «Сколько ему лет?»"),
        ]),
        group("Часть C · найдите ошибку и соберите", [
          fix("Where you work?", "you", "do you", "Нужен do: Where do you work?"),
          fix("Do you interested in history?", "Do", "Are", "interested — to be: Are you interested…?"),
          fix("What time does the shop opens?", "opens", "open", "После does — open."),
          ord("What music do you listen to?", "What music + do + you + listen + to?"),
          ord("How many times a week does she run?", "How many times a week + does + she + run?"),
        ]),
      ],
    },
    {
      id: "big", nav: "Итоговая", eyebrow: "Итоговая контрольная · весь курс", title: "Большая итоговая работа",
      theory: html(
        p("Задания по <b>всем урокам</b> вперемешку. Это самая сложная проверка: нужно каждый раз самому понять, какая тема перед вами."),
        p("Совет: перед ответом спросите себя: <b>есть ли в предложении глагол-действие?</b> Если нет — am / is / are. Если есть — do / does, -s или don't / doesn't.")
      ),
      groups: [
        group("Часть A · выберите", [
          ch("My flat ___ very big, but it's comfortable.", ["isn't", "doesn't", "hasn't"], "isn't", "big — какой → isn't."),
          ch("My flat ___ a balcony.", ["isn't got", "hasn't got", "doesn't got"], "hasn't got", "have got: flat = it → hasn't got."),
          ch("My sister ___ in a café at the weekend.", ["work", "works", "is work"], "works", "sister = she → works."),
          ch("___ your children like school?", ["Are", "Do", "Does"], "Do", "like — действие, children = they → Do."),
          ch("___ your children at school now?", ["Are", "Do", "Does"], "Are", "at school — где → Are."),
          ch("___ are these? — They're Jack's.", ["Whose", "Who's", "Who"], "Whose", "Чьи → Whose."),
          ch("Is this your umbrella? — No, it isn't ___.", ["my", "mine", "me"], "mine", "Без предмета → mine."),
          ch("We ___ a car, so we usually go by bus.", ["don't have", "haven't", "aren't have"], "don't have", "don't have (или haven't got)."),
          ch("I ___ to work by bike every day.", ["go", "am go", "goes"], "go", "I → go."),
          ch("He ___ TV in the morning.", ["never watches", "doesn't never watch", "never watch"], "never watches", "never без doesn't, he → watches."),
          ch("Where … he from? — He's from Italy. He's … .", ["is / Italian", "does / Italian", "is / Italy"], "is / Italian", "from → is; национальность → Italian."),
          ch("It ___ yesterday. Today it's sunny.", ["rains", "was rainy", "is rainy"], "was rainy", "yesterday → was."),
          ch("I'm … in football, but my husband finds it … .", ["interested / boring", "interesting / bored", "interested / bored"], "interested / boring", "Я — interested, футбол — boring."),
          ch("«Мне холодно.»", ["I'm cold.", "It is cold for me.", "I have cold."], "I'm cold.", "Состояние — через to be."),
          ch("We meet … Saturday mornings … 10 o'clock.", ["on / at", "in / at", "at / on"], "on / at", "on + день, at + время."),
          ch("Does Harry have any brothers? — No, he ___.", ["hasn't", "doesn't", "isn't"], "doesn't", "Вопрос с Does → No, he doesn't."),
          ch("Has Harry got any brothers? — No, he ___.", ["hasn't", "doesn't", "isn't"], "hasn't", "Вопрос с Has… got → No, he hasn't."),
          ch("… keys are on the table. Are they …?", ["This / your", "These / yours", "These / your"], "These / yours", "keys → These; без предмета → yours."),
        ]),
        group("Часть B · переведите на английский", [
          inp("«Мой брат не пьёт кофе.»", ["My brother doesn't drink coffee.", "My brother does not drink coffee."], "brother = he → doesn't drink.", "Переведите на английский"),
          inp("«Где работает твоя мама?»", ["Where does your mum work?", "Where does your mother work?", "Where does your mom work?"], "Where + does + your mum + work?", "Переведите на английский"),
          inp("«У неё есть собака.»", ["She has got a dog.", "She's got a dog.", "She has a dog."], "has got / has.", "Переведите на английский"),
          inp("«Это не мой телефон.»", ["This isn't my phone.", "This is not my phone.", "It isn't my phone.", "It is not my phone.", "It's not my phone."], "is not + my phone.", "Переведите на английский"),
          inp("«Ты обычно встаёшь рано?»", ["Do you usually get up early?"], "Do + you + usually + get up + early?", "Переведите на английский"),
          inp("«Мы из России.»", ["We are from Russia.", "We're from Russia."], "We are from Russia.", "Переведите на английский"),
        ]),
        group("Часть C · найдите ошибку", [
          fix("She have got three children.", "have", "has", "she → has got."),
          fix("Does your husband likes cooking?", "likes", "like", "После Does — like."),
          fix("Whose is this book? It's Annas.", "Annas", "Anna's", "Принадлежность → Anna's."),
          fix("They doesn't live here.", "doesn't", "don't", "they → don't."),
          fix("Are you work on Mondays?", "Are", "Do", "work — действие → Do you work…?"),
          fix("I'm usually go to bed at midnight.", "I'm", "I", "go — действие, am лишний: I usually go to bed…"),
        ]),
        group("Часть D · соберите предложение", [
          ord("What time does your sister finish work?", "What time + does + your sister + finish work?"),
          ord("These gloves aren't mine.", "These gloves + aren't + mine."),
          ord("My parents have got a house in the country.", "My parents + have got + a house + in the country."),
          ord("I hardly ever watch TV at the weekend.", "I + hardly ever + watch TV + at the weekend."),
        ]),
      ],
    },
  ],
};

// Added after a second check of the board: tasks on the new topics of lesson 1 (11 «Знакомство», 12 «Фразы с доски 2»).
extend(lesson, "t1", null, group("Часть D · знакомство и фразы с доски (темы 11–12)", [
  ch("A: This is my brother, Tom. B: ___", ["Nice to meet you.", "Nice meeting to you.", "I meet you."], "Nice to meet you.", "Nice to meet you."),
  ch("«Я из России, я русский.»", ["I'm from Russia. I'm Russian.", "I'm from Russian. I'm Russia.", "I from Russia. I Russian."], "I'm from Russia. I'm Russian.", "from + страна; национальность — Russian."),
  ch("The chemist's is ___, next to the bank.", ["on the right", "right", "at right"], "on the right", "on the right."),
  ch("I go swimming two ___ a week.", ["time", "times", "timing"], "times", "раз → times."),
  ch("Five ___ people work in our company.", ["hundred", "hundreds", "hundred of"], "hundred", "После числа — hundred."),
  inp("«Нам нужно принять решение.»", ["We need to make a decision.", "We need to take a decision."], "make / take a decision.", "Переведите на английский"),
]));

// Контрольные по урокам 7–12 и общая итоговая по второй половине курса.
extend(lesson, "big", null); // no change, kept for clarity of order
lesson.sections.splice(lesson.sections.findIndex(s => s.id === "big"), 0,
  {
    id: "t7", nav: "К7 · прошлое", eyebrow: "Контрольная 7 · урок 7", title: "Past Simple",
    theory: intro("7 «Прошедшее время»", "was / were · окончание -ed · неправильные глаголы · didn't и did · вопросы о прошлом"),
    groups: [
      group("Часть A · выберите", [
        ch("I ___ at work yesterday.", ["was", "were"], "was", "I → was."),
        ch("The children ___ at home on Sunday.", ["was", "were"], "were", "children = they → were."),
        ch("We ___ a film last night.", ["watch", "watched", "watching"], "watched", "last night → watched."),
        ch("She ___ in Kazan two years ago.", ["live", "lived", "lives"], "lived", "two years ago → lived."),
        ch("He ___ to London in May.", ["goed", "went", "gone"], "went", "go → went."),
        ch("They ___ a new car last month.", ["buyed", "bought", "buy"], "bought", "buy → bought."),
        ch("I ___ my keys at home.", ["didn't take", "didn't took", "not took"], "didn't take", "didn't + take."),
        ch("___ you see Anna yesterday?", ["Did", "Do", "Were"], "Did", "see — действие, прошлое → Did."),
        ch("Did they like the hotel? — Yes, they ___.", ["did", "were", "liked"], "did", "Yes, they did."),
        ch("___ the weather nice in Sochi?", ["Did", "Was", "Were"], "Was", "weather = it → Was."),
        ch("Where ___ you go last weekend?", ["did", "was", "were"], "did", "go — действие → did."),
        ch("How ___ your holiday?", ["was", "did", "were"], "was", "holiday = it → was."),
      ]),
      group("Часть B · напишите", [
        inp("start →", ["started"], "+ ed.", "Напишите форму прошедшего времени", "Обычный случай."),
        inp("carry →", ["carried"], "согласная + y → ied.", "Напишите форму прошедшего времени", "y меняется."),
        inp("see →", ["saw"], "see → saw.", "Напишите форму прошедшего времени", "Три буквы."),
        inp("I watched TV yesterday.", ["I didn't watch TV yesterday.", "I did not watch TV yesterday."], "watched → didn't watch.", "Сделайте отрицание"),
        inp("She went to the party.", ["Did she go to the party?"], "Did + she + go…?", "Превратите в вопрос"),
        inp("«Вчера мы были дома.»", ["We were at home yesterday.", "Yesterday we were at home."], "we → were.", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("They was at the cinema.", "was", "were", "they → were."),
        fix("I didn't saw him.", "saw", "see", "После didn't — see."),
        fix("Did she went home?", "went", "go", "После Did — go."),
        ord("What did you do at the weekend?", "What + did + you + do + at the weekend?"),
        ord("We didn't go to school on Monday.", "We + didn't + go to school + on Monday."),
      ]),
    ],
  },
  {
    id: "t8", nav: "К8 · сейчас", eyebrow: "Контрольная 8 · урок 8", title: "Present Continuous",
    theory: intro("8 «Прямо сейчас»", "am / is / are + -ing · правила -ing · отрицание и вопрос · «сейчас» или «обычно» · описание фото"),
    groups: [
      group("Часть A · выберите", [
        ch("Look! It ___.", ["snows", "is snowing"], "is snowing", "Look! → сейчас."),
        ch("I ___ dinner at the moment.", ["cook", "am cooking"], "am cooking", "at the moment → am cooking."),
        ch("My parents ___ TV every evening.", ["watch", "are watching"], "watch", "every evening → Present Simple."),
        ch("She usually ___ at 7, but today she's working late.", ["finishes", "is finishing"], "finishes", "usually → Present Simple."),
        ch("___ you listening to me?", ["Are", "Do", "Is"], "Are", "you → Are."),
        ch("He ___ today, he's ill.", ["isn't working", "doesn't working", "not working"], "isn't working", "isn't + working."),
        ch("Is she sleeping? — No, she ___.", ["isn't", "doesn't", "not"], "isn't", "No, she isn't."),
        ch("I ___ what you mean.", ["understand", "am understanding"], "understand", "understand — без -ing."),
        ch("A man is ___ a blue jacket.", ["wearing", "dressing", "having"], "wearing", "wear — быть одетым в."),
        ch("They ___ happy in this photo.", ["look", "are looking"], "look", "«выглядят» → look."),
      ]),
      group("Часть B · напишите", [
        inp("come →", ["coming"], "e уходит.", "Напишите глагол с -ing", "Без e."),
        inp("get →", ["getting"], "Буква удваивается.", "Напишите глагол с -ing", "Две t."),
        inp("She is working today.", ["She isn't working today.", "She is not working today."], "is → isn't.", "Сделайте отрицание"),
        inp("They are having lunch.", ["Are they having lunch?"], "Are + they + having…?", "Превратите в вопрос"),
        inp("«Что ты делаешь?»", ["What are you doing?"], "Сейчас → What are you doing?", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("Do you waiting for the bus?", "Do", "Are", "Сейчас → Are you waiting…?"),
        fix("I am work at home today.", "work", "working", "am + working."),
        ch("«Каждый день она ходит в спортзал.»", ["Every day she goes to the gym.", "Every day she is going to the gym.", "Every day she go to the gym."], "Every day she goes to the gym.", "Привычка → Present Simple."),
        ord("The children are playing in the garden.", "The children + are + playing + in the garden."),
      ]),
    ],
  },
  {
    id: "t9", nav: "К9 · there is", eyebrow: "Контрольная 9 · урок 9", title: "there is / there are",
    theory: intro("9 «there is / there are»", "there is и there are · some и any · предлоги места · дом, комнаты и город"),
    groups: [
      group("Часть A · выберите", [
        ch("___ a supermarket near my house.", ["There is", "There are", "It is"], "There is", "a supermarket → There is."),
        ch("___ six flats in our building.", ["There is", "There are"], "There are", "six flats → There are."),
        ch("___ any bread in the kitchen.", ["There isn't", "There aren't"], "There isn't", "bread не считается → isn't."),
        ch("___ any cafés near here?", ["Is there", "Are there"], "Are there", "cafés → Are there."),
        ch("Is there a bank in this street? — Yes, ___.", ["there is", "it is", "there are"], "there is", "Yes, there is."),
        ch("The towels are ___ the bathroom.", ["in", "on", "under"], "in", "Внутри → in."),
        ch("The bus stop is ___ the pharmacy.", ["next to", "next", "near to"], "next to", "next to."),
        ch("My house is ___ the school and the park.", ["between", "behind", "in front"], "between", "Между двумя → between."),
        ch("«холодильник» — ___", ["fridge", "cooker", "mirror"], "fridge", "fridge — холодильник."),
        ch("«почта» — ___", ["post office", "station", "supermarket"], "post office", "post office — почта."),
      ]),
      group("Часть B · напишите", [
        inp("There is a lamp in my room.", ["There isn't a lamp in my room.", "There is not a lamp in my room."], "is → isn't.", "Сделайте отрицание"),
        inp("There are some shops near here.", ["Are there any shops near here?"], "В вопросе some → any.", "Превратите в вопрос"),
        inp("(there / two chairs / in / the kitchen)", ["There are two chairs in the kitchen."], "two chairs → There are.", "Составьте предложение"),
        inp("«В моей комнате есть балкон.»", ["There is a balcony in my room.", "There's a balcony in my room."], "There is + a balcony.", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("There are a big park near my house.", "are", "is", "a park → There is."),
        fix("Is there any milk? — Yes, it is.", "it", "there", "Короткий ответ: Yes, there is."),
        fix("The cat is on the table, it sleeps under it.", "under", "on", "Если кот на столе, то on."),
        ord("Is there a pharmacy near here?", "Is + there + a pharmacy + near here?"),
      ]),
    ],
  },
  {
    id: "t10", nav: "К10 · can", eyebrow: "Контрольная 10 · урок 10", title: "can и can't",
    theory: intro("10 «can и can't»", "умения · can't и Can you…? · просьбы Can you…? и разрешения Can I…?"),
    groups: [
      group("Часть A · выберите", [
        ch("My sister ___ three languages.", ["can speak", "can speaks", "cans speak"], "can speak", "can + speak."),
        ch("I ___ ski at all.", ["can't", "don't can", "not can"], "can't", "can't + ski."),
        ch("___ you play the piano?", ["Can", "Do", "Are"], "Can", "Вопрос с can."),
        ch("Can he drive? — Yes, he ___.", ["can", "cans", "does"], "can", "Yes, he can."),
        ch("Can they come tonight? — No, they ___.", ["can't", "don't", "aren't"], "can't", "No, they can't."),
        ch("___ I use your pen? (просите разрешения)", ["Can", "Do", "Are"], "Can", "Can I…? — можно мне."),
        ch("___ you help me with this box? (просите друга)", ["Can", "May I", "Do"], "Can", "Can you…? — просьба."),
        ch("She can cook ___.", ["very well", "very good", "good very"], "very well", "well — как готовит."),
      ]),
      group("Часть B · напишите", [
        inp("I can swim.", ["I can't swim.", "I cannot swim."], "can → can't.", "Сделайте отрицание"),
        inp("He can play chess.", ["Can he play chess?"], "Can + he + play chess?", "Превратите в вопрос"),
        inp("(open the window — попросите собеседника)", ["Can you open the window, please?", "Can you open the window?"], "Can you + open the window.", "Составьте вежливую просьбу"),
        inp("«Можно мне воды, пожалуйста?»", ["Can I have some water, please?", "Can I have water, please?"], "Can I have + some water.", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("I don't can come tomorrow.", "don't", "can't", "can't come."),
        fix("Do you can drive?", "Do", "Can", "Can you drive?"),
        fix("She can drives very well.", "drives", "drive", "После can — drive."),
        ord("Can you help me please?", "Can + you + help me + please?"),
      ]),
    ],
  },
  {
    id: "t11", nav: "К11 · me · a / the", eyebrow: "Контрольная 11 · урок 11", title: "Местоимения и артикли",
    theory: intro("11 «me, him, them и артикли»", "местоимения после глагола · a / an / the · множественное число · like + it и + -ing"),
    groups: [
      group("Часть A · выберите", [
        ch("I saw Max yesterday. I know ___ well.", ["he", "him", "his"], "him", "После глагола → him."),
        ch("Call ___ when you arrive.", ["I", "me", "my"], "me", "После глагола → me."),
        ch("These are my books. Give ___ to me, please.", ["they", "them", "their"], "them", "books → them."),
        ch("My mother is ___ teacher.", ["a", "an", "—"], "a", "Перед профессией — a."),
        ch("He is ___ actor.", ["a", "an", "—"], "an", "actor → an."),
        ch("Close ___ door, please.", ["a", "the", "—"], "the", "Понятно какая → the."),
        ch("I love ___ music.", ["a", "the", "—"], "—", "Вообще → без артикля."),
        ch("There are three ___ in the park.", ["childs", "children", "childrens"], "children", "child → children."),
        ch("A lot of ___ live in this city.", ["people", "peoples", "persons"], "people", "people."),
        ch("She likes ___ books in the evening.", ["read", "reading", "reads"], "reading", "like + -ing."),
      ]),
      group("Часть B · напишите", [
        inp("city →", ["cities"], "согласная + y → ies.", "Напишите множественное число", "y меняется."),
        inp("woman →", ["women"], "Особая форма.", "Напишите множественное число", "Меняется гласная."),
        inp("I know Anna and Tom. → I know ___.", ["them"], "Anna and Tom → them.", "Впишите одно слово", "Они — …"),
        inp("«Я люблю эту песню. Она мне очень нравится.»", ["I like this song. I really like it.", "I love this song. I really like it."], "song → it.", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("I don't know she.", "she", "her", "После глагола → her."),
        fix("My father is doctor.", "doctor", "a doctor", "Перед профессией — a."),
        fix("There are five persons in the room.", "persons", "people", "person → people."),
        ord("I really like this city.", "I + really like + this city."),
      ]),
    ],
  },
  {
    id: "t12", nav: "К12 · еда", eyebrow: "Контрольная 12 · урок 12", title: "Еда, кафе и покупки",
    theory: intro("12 «Еда, кафе и покупки»", "что считается и что нет · some, any, a lot of · I'd like · цены и числа"),
    groups: [
      group("Часть A · выберите", [
        ch("Can I have ___ egg, please?", ["a", "an", "some"], "an", "egg → an."),
        ch("We need ___ bread.", ["a", "an", "some"], "some", "bread не считается → some."),
        ch("How ___ milk do you want?", ["much", "many"], "much", "milk не считается → much."),
        ch("How ___ bananas are there?", ["much", "many"], "many", "bananas считаются → many."),
        ch("There isn't ___ juice in the fridge.", ["some", "any", "a"], "any", "Отрицание → any."),
        ch("Would you like ___ tea?", ["some", "any", "many"], "some", "Предложение → some."),
        ch("I have ___ time before the train.", ["a few", "a little"], "a little", "time не считается → a little."),
        ch("«Мне, пожалуйста, кофе.»", ["I'd like a coffee, please.", "I like a coffee please.", "I'd like to a coffee."], "I'd like a coffee, please.", "I'd like + a coffee."),
        ch("How much ___ these shoes?", ["is", "are", "does"], "are", "shoes → are."),
        ch("«Это слишком дорого.»", ["It's too expensive.", "It's expensive too.", "It's very too expensive."], "It's too expensive.", "too — перед прилагательным."),
      ]),
      group("Часть B · напишите", [
        inp("60 →", ["sixty"], "60 = sixty.", "Напишите число словами", "Начинается на six."),
        inp("340 →", ["three hundred and forty", "three hundred forty"], "three hundred + and + forty.", "Напишите число словами", "three hundred and…"),
        inp("We have some sugar.", ["We don't have any sugar.", "We do not have any sugar."], "some → any в отрицании.", "Сделайте отрицание"),
        inp("Вы поели в кафе.", ["Can I have the bill, please?"], "Can I have the bill.", "Попросите счёт: «Можно счёт, пожалуйста?»"),
        inp("«Сколько стоит эта футболка?»", ["How much is this T-shirt?", "How much does this T-shirt cost?"], "How much is…?", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку и соберите", [
        fix("How much apples do we need?", "much", "many", "apples считаются → many."),
        fix("I don't have some money.", "some", "any", "В отрицании → any."),
        ch("«Мне, пожалуйста, бутерброд.»", ["I'd like a sandwich, please.", "I'd like to a sandwich, please.", "I like a sandwich, please."], "I'd like a sandwich, please.", "to нужно только перед глаголом."),
        ord("I'd like a cup of coffee.", "I'd like + a cup of coffee."),
      ]),
    ],
  },
  {
    id: "big2", nav: "Итоговая 2", eyebrow: "Итоговая контрольная · уроки 7–12", title: "Большая работа по второй половине курса",
    theory: html(
      p("Задания по урокам <b>7–12</b> вперемешку: прошлое, «сейчас», there is, can, местоимения с артиклями и еда."),
      p("Совет: сначала определите время. Есть yesterday или last — прошлое. Есть now или Look! — Present Continuous. Есть usually или every day — Present Simple.")
    ),
    groups: [
      group("Часть A · выберите", [
        ch("Yesterday I ___ my grandmother.", ["visit", "visited", "am visiting"], "visited", "Yesterday → Past Simple."),
        ch("Be quiet! The baby ___.", ["sleeps", "is sleeping"], "is sleeping", "Сейчас → is sleeping."),
        ch("We ___ to the cinema every Friday.", ["go", "are going", "went"], "go", "every Friday → Present Simple."),
        ch("___ there any milk in the fridge?", ["Is", "Are", "Does"], "Is", "milk → Is there."),
        ch("I ___ swim, but I can't ski.", ["can", "can to", "am can"], "can", "can + swim."),
        ch("Where ___ you last night?", ["was", "were", "did"], "were", "you → were."),
        ch("Where ___ you go last night?", ["was", "were", "did"], "did", "go — действие → did."),
        ch("I know Anna, but I don't know ___ brother.", ["she", "her", "hers"], "her", "her + brother — чей."),
        ch("Call ___ tomorrow, please.", ["I", "me", "my"], "me", "После глагола → me."),
        ch("There are a lot of ___ in the street.", ["people", "peoples", "persons"], "people", "people."),
        ch("Can I have ___ water, please?", ["a", "some", "many"], "some", "water → some."),
        ch("My brother is ___ engineer.", ["a", "an", "—"], "an", "engineer → an."),
      ]),
      group("Часть B · напишите", [
        inp("«Вчера мы ходили в кино.»", ["We went to the cinema yesterday.", "Yesterday we went to the cinema."], "go → went.", "Переведите на английский"),
        inp("«Сейчас я готовлю ужин.»", ["I'm cooking dinner now.", "I am cooking dinner now."], "Сейчас → am cooking.", "Переведите на английский"),
        inp("«В моей комнате есть два окна.»", ["There are two windows in my room."], "two windows → There are.", "Переведите на английский"),
        inp("«Я не умею водить машину.»", ["I can't drive.", "I cannot drive.", "I can't drive a car.", "I cannot drive a car."], "can't + drive.", "Переведите на английский"),
        inp("«У нас нет хлеба.»", ["We don't have any bread.", "We do not have any bread.", "We haven't got any bread."], "don't have any bread.", "Переведите на английский"),
      ]),
      group("Часть C · найдите ошибку", [
        fix("I didn't went to work yesterday.", "went", "go", "После didn't — go."),
        fix("Do you working now?", "Do", "Are", "Сейчас → Are you working?"),
        fix("There is two cafés in my street.", "is", "are", "two cafés → are."),
        fix("She can speaks English.", "speaks", "speak", "После can — speak."),
        fix("I saw they at the party.", "they", "them", "После глагола → them."),
        fix("How much eggs do we need?", "much", "many", "eggs считаются → many."),
      ]),
    ],
  }
);
lesson.position = 14;

export default lesson;
