// Builds lesson JSON files and one migration from the lesson sources in this folder.
// Usage: node supabase/lessons/build.mjs <migration-name>
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const name = process.argv[2];
if (!name) { console.error("Usage: node supabase/lessons/build.mjs <migration-name>"); process.exit(1); }

const files = readdirSync(here).filter(f => /^\d+-.+\.mjs$/.test(f)).sort((a, b) => parseInt(a) - parseInt(b));
const problems = [];
const sql = ["-- Lessons generated by supabase/lessons/build.mjs — edit the .mjs sources, not this file."];

for (const f of files) {
  const { default: L } = await import(join(here, f));
  const content = { ...(L.steps === false ? { steps: false } : {}), sections: L.sections };
  const ids = new Set();
  let items = 0;
  for (const s of L.sections) {
    if (ids.has(s.id)) problems.push(`${f}: duplicate section id ${s.id}`);
    ids.add(s.id);
    for (const g of s.groups) for (const it of g.items) {
      items++;
      const where = `${f} › ${s.id} › ${g.title} › ${it.q || it.a[0]}`;
      if (it.t === "choice" && !it.o.includes(it.a)) problems.push(`${where}: answer not among options`);
      if (it.t === "choice" && new Set(it.o).size !== it.o.length) problems.push(`${where}: duplicate options`);
      if (it.b) for (const k of Object.keys(it.b)) if (!it.o.includes(k)) problems.push(`${where}: explanation for missing option "${k}"`);
      if (it.t === "fix" && it.w < 0) problems.push(`${where}: wrong word not found`);
      if (!it.ex) problems.push(`${where}: no explanation`);
    }
  }
  const json = JSON.stringify(content);
  if (json.includes("$lesson$")) problems.push(`${f}: contains $lesson$`);
  writeFileSync(join(here, "..", `lesson-${L.slug}.json`), JSON.stringify({ slug: L.slug, title: L.title, subtitle: L.subtitle, ...content }));
  const q = s => "'" + s.replace(/'/g, "''") + "'";
  sql.push(`
-- Lesson ${L.position}: ${L.title} (${L.sections.length} sections, ${items} items)
insert into public.lessons (slug, title, subtitle, position, content)
values (${q(L.slug)}, ${q(L.title)}, ${q(L.subtitle)}, ${L.position}, $lesson$${json}$lesson$::jsonb)
on conflict (slug) do update set title = excluded.title, subtitle = excluded.subtitle, position = excluded.position, content = excluded.content, updated_at = now();`);
  console.log(`${f}: ${L.sections.length} sections, ${items} items`);
}

// The lesson vocabulary («слово — перевод» in lists and tables) becomes the tap-to-translate dictionary.
const dict = {};
const addWord = (en, ru) => {
  en = en.trim().toLowerCase().replace(/\s+/g, " ").replace(/^(a|an|the) /, "");
  ru = ru.trim().replace(/\s+/g, " ");
  if (!en || !ru || en.length > 28) return;
  if (!/^[a-z][a-z0-9 '\u2019\/-]*$/.test(en)) return;
  if (!/[\u0410-\u044f\u0401\u0451]/.test(ru)) return;
  if (!dict[en]) dict[en] = ru;
};
for (const f of files) {
  const { default: L } = await import(join(here, f));
  for (const s of L.sections) {
    const html = s.theory || "";
    for (const m of html.matchAll(/<li>([^<]{2,80})<\/li>/g)) {
      const pair = m[1].match(/^([^\u2014]+)\u2014(.+)$/);
      if (pair) addWord(pair[1], pair[2]);
    }
    for (const m of html.matchAll(/<td>([^<]{1,40})<\/td>\s*<td>([^<]{1,60})<\/td>/g)) addWord(m[1], m[2]);
  }
}
writeFileSync(join(here, "..", "..", "src", "dictionary-lessons.js"),
  "// Словарь из уроков. Файл создаётся автоматически: node supabase/lessons/build.mjs\n"
  + "export default " + JSON.stringify(dict, null, 0) + ";\n");
console.log("словарь уроков:", Object.keys(dict).length, "слов");


// Проверка покрытия: каждое английское слово из уроков должно переводиться по тапу.
// Исключения (намеренно неверные написания, анаграммы, обрывки) перечислены в no-translate.txt.
const { translate } = await import("../../src/translate.js?t=" + Date.now());
const skip = new Set(readFileSync(join(here, "no-translate.txt"), "utf8")
  .split("\n").map(x => x.trim().toLowerCase()).filter(x => x && !x.startsWith("#")));
const seen = new Map();
for (const f of files) {
  const { default: L } = await import(join(here, f));
  const texts = [];
  for (const s of L.sections) {
    texts.push(String(s.theory || "").replace(/<[^>]+>/g, " "));
    for (const g of s.groups || []) for (const it of g.items || []) {
      for (const k of ["q", "ex", "p", "h"]) if (typeof it[k] === "string") texts.push(it[k]);
      if (Array.isArray(it.a)) texts.push(...it.a); else if (typeof it.a === "string") texts.push(it.a);
      if (Array.isArray(it.o)) texts.push(...it.o);
      if (Array.isArray(it.w)) texts.push(...it.w);
    }
  }
  for (const t of texts) for (const m of String(t).matchAll(/[A-Za-z][A-Za-z\u00c0-\u00ff'\u2019]+/g)) {
    const raw = m[0], w = raw.toLowerCase().replace("\u2019", "'");
    if (!seen.has(w)) seen.set(w, { n: 0, lower: false, file: f });
    const rec = seen.get(w);
    rec.n++;
    if (raw[0] === raw[0].toLowerCase()) rec.lower = true;
  }
}
// Слова с большой буквы, которые нигде не встречаются со строчной, считаем именами.
const missing = [...seen].filter(([w, r]) => r.lower && w.length > 3 && !skip.has(w) && !translate(w));
if (missing.length) {
  console.warn("без перевода по тапу (" + missing.length + "): " + missing.map(([w, r]) => `${w} — ${r.file}`).join(", "));
  console.warn("добавьте перевод в src/dictionary.js или слово в supabase/lessons/no-translate.txt");
} else {
  console.log("перевод по тапу: покрыты все слова уроков");
}

if (problems.length) { console.error(problems.join("\n")); process.exit(1); }
// Timestamp must be later than every migration already applied, so take the newest one into account.
const existing = readdirSync(join(here, "..", "migrations")).filter(f => /^\d{14}_/.test(f)).map(f => f.slice(0, 14)).sort();
const now = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
const last = existing[existing.length - 1] || "";
const stamp = now > last ? now : String(BigInt(last) + 1n);
const out = join(here, "..", "migrations", `${stamp}_${name}.sql`);
writeFileSync(out, sql.join("\n") + "\n");
console.log("wrote", out);
