// A third, wrong but typical option for choice tasks that had only two: with two options half the answers can be guessed.
// Keyed by lesson slug and the exact task text: [extra option, why it is wrong]. build.mjs inserts it; the right answer and item ids stay the same.
// Tasks where the choice is two-way by nature (True / False, 's = is / has, syllables, Can I / Can you) are left as they are.

export default {
  "food-cafe": {
    "How ___ sugar do you take?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "How ___ tomatoes do we need?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "How ___ water do you drink every day?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "I have ___ friends here.": ["a lot","a lot без of не ставится перед существительным."],
  },
  "have-got": {
    "I ___ a new laptop.": ["has","has — только с he / she / it, и в этой теме нужно ещё got."],
    "My sister ___ a beautiful necklace.": ["have","have — для I / you / we / they, а здесь одно лицо; и без got."],
    "We ___ two cats.": ["has","has — только с he / she / it, и в этой теме нужно ещё got."],
    "Tom ___ blue eyes.": ["have","have — для I / you / we / they, а здесь одно лицо; и без got."],
    "My parents ___ a big house.": ["has","has — только с he / she / it, и в этой теме нужно ещё got."],
    "Our flat ___ a balcony.": ["have","have — для I / you / we / they, а здесь одно лицо; и без got."],
    "You ___ a lot of books!": ["has","has — только с he / she / it, и в этой теме нужно ещё got."],
    "I ___ a pen. Can I use yours?": ["don't got","don't got не бывает: отрицание — haven't got / hasn't got."],
    "My brother ___ a car.": ["don't got","don't got не бывает: отрицание — haven't got / hasn't got."],
    "She ___ any pets.": ["don't got","don't got не бывает: отрицание — haven't got / hasn't got."],
    "___ you got a minute?": ["Do","С got вопрос строится без do: Have / Has … got?"],
    "___ Evan got any sisters?": ["Do","С got вопрос строится без do: Have / Has … got?"],
    "___ they got a car?": ["Do","С got вопрос строится без do: Have / Has … got?"],
    "___ your flat got a balcony?": ["Do","С got вопрос строится без do: Have / Has … got?"],
    "Everybody ___ happy today.": ["am","am — только с I."],
    "My brother ___ a new motorbike.": ["have","have — для I / you / we / they, а здесь одно лицо; и без got."],
  },
  "past-simple": {
    "I ___ at the cinema yesterday.": ["is","is — настоящее время, а речь о прошлом."],
    "My parents ___ very tired last night.": ["are","are — настоящее время, а речь о прошлом."],
    "The weather ___ terrible on Sunday.": ["is","is — настоящее время, а речь о прошлом."],
    "You ___ right!": ["are","are — настоящее время, а речь о прошлом."],
    "We ___ at the same school in 2019.": ["are","are — настоящее время, а речь о прошлом."],
    "The shops ___ closed.": ["are","are — настоящее время, а речь о прошлом."],
    "They ___ football every Sunday.": ["plays","plays — для he / she / it, а здесь they."],
    "We ___ at the seaside last July.": ["are","are — настоящее время, а речь о прошлом."],
  },
  "present-continuous": {
    "I usually ___ at 7, but today I'm working late.": ["finishing","Без am / is / are форма finishing не работает."],
    "Be quiet! The baby ___.": ["sleeping","Без am / is / are форма sleeping не работает."],
    "My sister ___ in a hospital.": ["working","Без am / is / are форма working не работает."],
    "Where's Tom? — He ___ a shower.": ["having","Без am / is / are форма having не работает."],
    "We ___ to the sea every summer.": ["going","Без am / is / are форма going не работает."],
    "Look! It ___.": ["raining","Без am / is / are форма raining не работает."],
    "I ___ what you mean.": ["understanding","Без am / is / are форма understanding не работает."],
    "She ___ a new phone.": ["wanting","Без am / is / are форма wanting не работает."],
    "Hurry up! The bus ___.": ["coming","Без am / is / are форма coming не работает."],
    "My father ___ coffee every morning.": ["drinking","Без am / is / are форма drinking не работает."],
    "Why ___ you wearing a coat? It's hot!": ["does","does — для he / she / it."],
    "How often ___ you go to the gym?": ["does","does — для he / she / it."],
    "They ___ very happy in this photo.": ["looking","Без am / is / are форма looking не работает."],
    "Listen! Somebody ___.": ["singing","Без am / is / are форма singing не работает."],
    "I ___ my homework at the moment.": ["doing","Без am / is / are форма doing не работает."],
    "My parents ___ TV every evening.": ["watching","Без am / is / are форма watching не работает."],
    "Sorry, I can't talk. I ___ the bus.": ["catching","Без am / is / are форма catching не работает."],
    "I ___ this song!": ["loving","Без am / is / are форма loving не работает."],
    "What ___ you usually do after work?": ["does","does — для he / she / it."],
  },
  "present-simple-he-she-it": {
    "My sister ___ in a hospital.": ["working","Без am / is / are форма working не работает."],
    "They ___ in a big house.": ["living","Без am / is / are форма living не работает."],
    "Liam ___ his job.": ["loving","Без am / is / are форма loving не работает."],
    "The film ___ at 8 p.m.": ["starting","Без am / is / are форма starting не работает."],
    "My parents ___ TV every evening.": ["watching","Без am / is / are форма watching не работает."],
    "40 — ___": ["fourteen","fourteen — 14."],
  },
  "present-simple-i-you-we-they": {
    "___ you tired?": ["Does","Does — для he / she / it. И здесь нет действия — нужен to be."],
  },
  "pronouns-articles": {
    "People ___ very friendly here.": ["am","am — только с I."],
  },
  "questions-do-does": {
    "___ you get up early?": ["Is","Is — для вопросов с to be (кто, где, какой). Здесь есть действие."],
    "___ he know Jenny?": ["Is","Is — для вопросов с to be (кто, где, какой). Здесь есть действие."],
    "___ your parents live near you?": ["Is","Is — для вопросов с to be (кто, где, какой). Здесь есть действие."],
    "___ she drink coffee?": ["Is","Is — для вопросов с to be (кто, где, какой). Здесь есть действие."],
    "___ Ron and Jan live here?": ["Is","Is — для вопросов с to be (кто, где, какой). Здесь есть действие."],
    "I ___ in a café now.": ["is","is — для he / she / it, а здесь I."],
    "___ she play tennis every week?": ["Are","Are — для you / we / they и для вопросов без действия."],
    "___ she a singer?": ["Do","Do — для I / you / we / they и для действий."],
    "___ they on the bus?": ["Does","Does — для he / she / it и для действий."],
    "Why ___ he in France?": ["do","do — для I / you / we / they."],
    "It ___ cold today.": ["aren't","aren't — для you / we / they."],
    "They ___ like animals.": ["doesn't","doesn't — для he / she / it."],
    "Where ___ you? — I'm at home.": ["does","does — для he / she / it."],
    "What ___ the dog eat?": ["do","do — для I / you / we / they."],
    "He ___ an accountant.": ["aren't","aren't — для you / we / they."],
    "___ you interested in football?": ["Does","Does — для he / she / it и для действий."],
    "We ___ make too much noise at night.": ["doesn't","doesn't — для he / she / it."],
    "How ___ brothers have you got?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "How ___ is this painting?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "I don't drink ___ tea.": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "She hasn't got ___ friends here.": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "___ you at home now?": ["Does","Does — для he / she / it и для действий."],
    "How ___ sugar do you want?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
  },
  "tests": {
    "The hotel is famous for ___ view.": ["its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "I'm ___ in art.": ["interest","interest — существительное или глагол; нужна форма на -ed или -ing."],
    "My earrings ___ in the bathroom.": ["am","am — только с I."],
    "My grandparents ___ a small house in the country.": ["has","has — только с he / she / it, и в этой теме нужно ещё got."],
    "Anna ___ long dark hair.": ["have","have — для I / you / we / they, а здесь одно лицо; и без got."],
    "We ___ any bread. Can you buy some?": ["don't got","don't got не бывает: отрицание — haven't got / hasn't got."],
    "Everybody ___ tired after the trip.": ["am","am — только с I."],
    "___ he a good cook?": ["Do","Do — для I / you / we / they и для действий."],
    "___ he cook well?": ["Are","Are — для you / we / they и для вопросов без действия."],
    "___ you hungry?": ["Does","Does — для he / she / it и для действий."],
    "How ___ money have you got?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "How ___ languages do you speak?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "I ___ at work yesterday.": ["is","is — настоящее время, а речь о прошлом."],
    "The children ___ at home on Sunday.": ["are","are — настоящее время, а речь о прошлом."],
    "Look! It ___.": ["snowing","Без am / is / are форма snowing не работает."],
    "I ___ dinner at the moment.": ["cooking","Без am / is / are форма cooking не работает."],
    "My parents ___ TV every evening.": ["watching","Без am / is / are форма watching не работает."],
    "She usually ___ at 7, but today she's working late.": ["finishing","Без am / is / are форма finishing не работает."],
    "I ___ what you mean.": ["understanding","Без am / is / are форма understanding не работает."],
    "They ___ happy in this photo.": ["looking","Без am / is / are форма looking не работает."],
    "___ six flats in our building.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ any bread in the kitchen.": ["It isn't","It isn't — «это не», а здесь «нет»: there isn't / there aren't."],
    "___ any cafés near here?": ["Is it","Is it — «это?», а здесь спрашиваем «есть ли»."],
    "How ___ milk do you want?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "How ___ bananas are there?": ["a lot","a lot без of здесь не работает; в вопросе How… — much или many."],
    "I have ___ time before the train.": ["a lot","a lot без of не ставится перед существительным."],
    "Be quiet! The baby ___.": ["sleeping","Без am / is / are форма sleeping не работает."],
  },
  "there-is": {
    "___ a big park near my house.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ three bedrooms in our flat.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ a lot of people in the shop.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ some water in the bottle.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ two cafés and a bank in my street.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "___ any good restaurants in your town?": ["Is it","Is it — «это?», а здесь спрашиваем «есть ли»."],
    "There ___ any children in the park.": ["don't","После there — is / are, не don't."],
    "___ five people in the room.": ["It is","It is — «это», а здесь «есть, находится»: there is / there are."],
    "There ___ any milk in the fridge.": ["don't","После there — is / are, не don't."],
  },
  "to-be": {
    "___ raining again.": ["Its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "The company changed ___ name.": ["its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "___ my birthday tomorrow.": ["Its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "Look at that bird! ___ wings are blue.": ["Its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "I like this hotel. ___ near the beach.": ["Its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "The cat is sleeping in ___ bed.": ["its'","Формы its' не существует: либо it's (= it is), либо its (его, её)."],
    "This book is very ___.": ["interest","interest — существительное или глагол; нужна форма на -ed или -ing."],
    "Are you ___ in football?": ["interest","interest — существительное или глагол; нужна форма на -ed или -ing."],
    "I'm ___. Let's watch something else.": ["bore","bore — глагол; нужна форма на -ed или -ing."],
    "The lesson was ___, I almost fell asleep.": ["bore","bore — глагол; нужна форма на -ed или -ing."],
    "After work I'm always ___.": ["tire","tire — глагол (и «шина»); нужна форма на -ed или -ing."],
    "We're really ___ about our trip!": ["excite","excite — глагол; нужна форма на -ed или -ing."],
    "I ___ ill yesterday.": ["is","is — настоящее время, а речь о прошлом."],
    "The tickets ___ very expensive last year.": ["are","are — настоящее время, а речь о прошлом."],
    "___ you at the party on Saturday?": ["Are","Are — настоящее время, а речь о прошлом."],
    "The hotel ___ clean, so we left.": ["isn't","isn't — настоящее время, а речь о прошлом."],
    "My parents ___ at home last night.": ["are","are — настоящее время, а речь о прошлом."],
  },
  "whose": {
    "These gloves ___ very warm.": ["am","am — только с I."],
    "My sunglasses ___ in the car.": ["am","am — только с I."],
    "This necklace ___ a present from my mum.": ["am","am — только с I."],
    "Your keys ___ on the table.": ["am","am — только с I."],
    "Whose notebook ___ this?": ["am","am — только с I."],
    "Whose gloves ___ these?": ["am","am — только с I."],
    "My gloves ___ in my bag.": ["am","am — только с I."],
  },
};
